### ISSUE TITLE
Gta Not working

### ISSUE THREAD

**Issue by JCrobotss1234** [ZippyCodeYT/Zippy_Codes#12]
Traceback (most recent call last):
  File "/Users/jacobthegamer/PycharmProjects/pythonProject/main.py", line 1, in <module>
    from ursina import *
  File "/Users/jacobthegamer/PycharmProjects/pythonProject/venv/lib/python3.10/site-packages/ursina/__init__.py", line 10, in <module>
    from ursina.window import instance as window
  File "/Users/jacobthegamer/PycharmProjects/pythonProject/venv/lib/python3.10/site-packages/ursina/window.py", line 5, in <module>
    app = Ursina()
NameError: name 'Ursina' is not defined 

Plz help

**Comment by WronaDEV** [comment]
install ursina package
